services:
  - type: web
    name: ruijie-bot
    env: python
    repo: https://github.com/naing295830-bit/edgetunnel
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
